name: PHP-CI

on: [push, pull_request]

jobs:
  deploy_dev:
    strategy:
      fail-fast: false
      matrix:
        regions:
          - name: 'us-west-1'
            bucket: 'bucket-one'
            url: 'https://example-one.com'
          - name: 'eu-central-1'
            bucket: 'bucket-two'
            url: 'https://example-two.com'

    name: Deployment (DEV)${{ matrix.regions.placeholder }}
    uses: ./.github/workflows/base-serverless-deploy.yml
    with:
      environment-name: 'dev'
      environment-region: ${{ matrix.regions.name }}
      environment-assets-bucket: ${{ matrix.regions.bucket }}
      environment-url: ${{ matrix.regions.url }}
    secrets: inherit