name: PHP-CI

on: [push, pull_request]

jobs:
  coding_standards:
    runs-on: ubuntu-22.04
    env:
      PHP_EXTENSIONS_CACHE_KEY: cache-extensions-openswoole-v1

    steps:
      -   name: Checkout.
          uses: actions/checkout@v4

      -   name: Setup cache environment
          id: cache-extensions
          uses: shivammathur/cache-extensions@v1
          with:
            php-version: '8.2'
            extensions: openswoole
            key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

      -   name: Cache extensions
          uses: actions/cache@v4
          with:
            path: ${{ steps.cache-extensions.outputs.dir }}
            key: ${{ steps.cache-extensions.outputs.key }}

      -   name: Setup PHP
          uses: voodooism/setup-php@4eb1919d226aeb231ea69834616a33342a87882d
          with:
            php-version: '8.2'
            coverage: 'none'
            extensions: openswoole

      - name: php m
        run: php -m
