name: PHP-CI

on: [push, pull_request]

jobs:
  coding_standards:
    runs-on: ubuntu-latest
    env:
      PHP_EXTENSIONS: pdo_sqlite, pkcs11, openswoole
      PHP_EXTENSIONS_CACHE_KEY: cache-extensions-pdo_sqlite-openswoole-pkcs11

    steps:
      -   name: Checkout.
          uses: actions/checkout@v4

      -   name: Setup cache environment
          id: cache-extensions
          uses: shivammathur/cache-extensions@v1
          with:
            php-version: '8.2'
            extensions: ${{ env.PHP_EXTENSIONS }}
            key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

      -   name: Cache extensions
          uses: actions/cache@v4
          with:
            path: ${{ steps.cache-extensions.outputs.dir }}
            key: ${{ steps.cache-extensions.outputs.key }}

      -   name: Setup PHP ${{ matrix.php }}
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            coverage: 'none'
            extensions: ${{ env.PHP_EXTENSIONS }}