name: PHP-CI

on: [push, pull_request]

jobs:
  coding_standards:
    runs-on: ubuntu-latest
    env:
      PHP_EXTENSIONS: openswoole
      PHP_EXTENSIONS_CACHE_KEY: cache-extensions-openswoole

    steps:
      -   name: Checkout.
          uses: actions/checkout@v4

      -   name: Setup PHP ${{ matrix.php }}
          uses: shivammathur/setup-php@verbose
          with:
            php-version: '8.2'
            coverage: 'none'
            extensions: ${{ env.PHP_EXTENSIONS }}